NovalnetGlobalConfigurationTab=Novalnet Global Configuration
vendorIdLabel=Merchant ID*
authCodeLabel=Authentication code*
productIdLabel=Project ID*
tariffIdLabel=Tariff ID*
accessKeyLabel=Payment access key*
gatewaytimeoutLabel=Gateway Timeout (in seconds)
proxyserverLabel=Proxy Server
onholdConfirmationStatusLabel = Onhold order status
orderCancelStatusLabel=Cancellation order status
paymentLogoLabel=Upload payment logo
NovalnetDisableConfigration = false
NovalnetCreditCardTab=Credit Card
cc3dLabel=Enable 3D secure
cc3dFraudcheckLabel=Force 3D secure on predefined conditions
novalnetCcStandardStyleLabelLabel=Standard - Label
novalnetCcStandardStyleFieldLabel=Standard - Input field
novalnetCcStandardStyleCssLabel=Standard - CSS
NovalnetDirectDebitSEPATab=Direct Debit SEPA
sepaDueDateLabel=SEPA Payment duration (in days)
NovalnetInvoiceTab=Invoice
invoiceDueDateLabel=Payment due date (in days)
NovalnetPrepaymentTab=Prepayment
NovalnetInstantBankTransferTab=Online Bank Transfer
NovalnetPayPalTab=PayPal
NovalnetiDealTab=iDEAL
NovalnetEPSTab=eps
NovalnetGiropayTab=giropay
NovalnetPrzelewy24Tab=Przelewy24
NovalnetBarzahlenTab=Barzahlen
cashpaymentDueDateLabel=Slip expiry date (in days)
NovalnetMerchantScriptManagementTab=Merchant script management
callbackTestModeLabel=Deactivate IP address control (for test purpose only)
enableEmailLabel=Enable E-mail notification for callback
emailToLabel=E-mail address (To)
emailToTooltip=E-Mail address of the recipient
emailBccLabel=E-mail address (Bcc)
emailBccTooltip=E-Mail address of the recipient for BCC
paymentDescriptionLabel=Payment description
paymentNameLabel=Payment name
callbackOrderStatusLabel=Callback order status
paymentActiveLabel=Enable payment method
testModeLabel=Enable test mode
orderCompletionStatusLabel=Order completion status
paymentGuaranteeActiveLabel=Enable payment guarantee
paymentPendingStatusLabel=Order status for the pending payment
onHoldLabel=Minimum transaction limit for authorization (in minimum unit of currency. E.g. enter 100 which is equal to 1.00)
guaranteeMinAmountLabel=Minimum order amount (in minimum unit of currency. E.g. enter 100 which is equal to 1.00)
paymentGuaranteeForceActiveLabel=Force Non-Guarantee payment
vendorIdTooltip=Enter Novalnet merchant ID
authCodeTooltip=Enter Novalnet authentication code
productIdTooltip=Enter Novalnet project ID
tariffIdTooltip=Enter Novalnet tariff ID
accessKeyTooltip=Enter the Novalnet payment access key
onHoldTooltip=In case the order amount exceeds the mentioned limit, the transaction will be set on-hold till your confirmation of the transaction. You can leave the field empty if you wish to process all the transactions as on-hold.
cashpaymentDueDateTooltip=Enter the number of days to pay the amount at store near you. If the field is empty, 14 days will be set as default
paypalOnHoldTooltip=In order to use this option you must have billing agreement option enabled in your PayPal account. Please contact your account manager at PayPal
guaranteeMinAmountTooltip=This setting will override the default setting made in the minimum order amount. Note that amount should be in the range of 9,99 EUR 
invoiceDueDateTooltip=Enter the number of days to transfer the payment amount to Novalnet (must be greater than 7 days). In case if the field is empty, 14 days will be set as due date by default
paymentGuaranteeStatus=Order status for the pending payment
gatewaytimeoutTooltip=If the processing time of the order exceeds the time limit of the interface, the order will not be executed
proxyserverTooltip=Enter the proxy server
sepaDueDateTooltip=Enter the number of days after which the payment should be processed (must be between 2 and 14 days) 
allowedCountryLabel=Allowed Countries
onholdCapture=Capture
onholdAuthorize=Authorize
paymentActionLabel=Payment action
minimumOrderAmountLabel=Minimum Order Amount
maximumOrderAmountLabel=Maximum Order Amount
minimumOrderAmountTooltip=Minimum Order Amount to offer this Payment (in minimum unit of currency. E.g. enter 100 which is equal to 1.00)
maximumOrderAmountTooltip=Maximum Order Amount to offer this Payment (in minimum unit of currency. E.g. enter 100 which is equal to 1.00)
